export { default as About } from "./About";
export { default as Certifications } from "./Certifications";
export { default as Education } from "./Education";
export { default as Expereince } from "./Expereince";
export { default as Footer } from "./Footer";
export { default as Header } from "./Header";
export { default as Projects } from "./Projects";
export { default as Skills } from "./Skills";
export { default as Tools } from "./Tools";