import React from "react";
import { GoOrganization } from "react-icons/go";


const ExperienceCard = () => {
    return (
        <div className="w-full max-w-sm overflow-hidden bg-gray-100 rounded-lg shadow-lg hover:bg-blue-50 hover:shadow-xl mx-2 transition ease-in mt-8 md:mt-0 group">
            <img className="object-cover object-center w-full h-56 group-hover:opacity-85 transition ease-in" src="https://images.unsplash.com/photo-1517841905240-472988babdf9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=334&q=80" alt="avatar" />

            <div className="flex items-center px-4 py-3 bg-gray-800">
                <GoOrganization className="mx-2 h-6 md:h-8 w-auto text-gray-200" />
                <h1 class="mx-3 text-lg font-semibold text-gray-200">Company Name</h1>
            </div>

            <div class="px-6 py-4">
                <p class="py-2 text-gray-800 font-semibold">Full Stack maker & UI / UX Designer , love hip hop music Author of Building UI.
                <span className="text-gray-600 text-md">&nbsp;Year served</span>
                </p>

                <h1 className="text-md mt-2 md:mt-4 text-gray-700 italic font-semibold">Job Description : </h1>
                <div className="flex items-center mt-1 text-gray-600 px-4">
                    <ul className="list-disc">
                        <li>I helped my team analyze various log data generated by the system using python to draw some insights.</li>
                        <li>I worked on improving the accuracy of the machine learning algorithm.</li>
                        <li>I developed a simple front-end website for our mentors to visualize all the insights we've drawn using the machine learning algorithm.</li>
                    </ul>
                </div>
            </div>
        </div>
    )
}

export default ExperienceCard;